# Root directories
root = "."
testdata_dir = "testdata"
tmp_dir = "tmp"

[build]
  # Arguments passed to the binary during build
  args_bin = []

  # Output binary path
  bin = "tmp\\main.exe"

  # Build command
  cmd = "go build -o ./tmp/main.exe ."

  # Delay before restarting the build (milliseconds)
  delay = 1000

  # Directories to exclude from watching
  exclude_dir = ["assets", "tmp", "vendor", "testdata"]

  # Files to exclude by name
  exclude_file = []

  # Regex to exclude specific files (e.g., tests)
  exclude_regex = ["_test.go"]

  # Whether to rebuild on unchanged files
  exclude_unchanged = false

  # Follow symbolic links during file watching
  follow_symlink = false

  # Path to full binary if specified, leave empty to use `bin`
  full_bin = ""

  # Directories to include for watching (overrides `exclude_dir`)
  include_dir = []

  # File extensions to watch for changes
  include_ext = ["go", "tpl", "tmpl", "html"]

  # Specific files to include for watching
  include_file = []

  # Time to wait before force-killing the build process (default 0)
  kill_delay = "0s"

  # Log build errors to specified file
  log = "build-errors.log"

  # Enable polling mode instead of file watching
  poll = false

  # Poll interval in milliseconds (used if `poll` is true)
  poll_interval = 0

  # Commands to run after the build
  post_cmd = []

  # Commands to run before the build
  pre_cmd = []

  # Rerun the build command without restarting watcher
  rerun = false

  # Delay for rerunning in milliseconds
  rerun_delay = 500

  # Send interrupt signal instead of kill signal to stop the build
  send_interrupt = false

  # Stop watcher on build error
  stop_on_error = false

[color]
  # Customize colors for different log outputs
  app = ""
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"

[log]
  # Only log main messages, not all events
  main_only = false

  # Include timestamps in logs
  time = true

[misc]
  # Automatically clean up temporary files on exit
  clean_on_exit = true

[proxy]
  # Port for the app if using a proxy
  app_port = 8080

  # Enable or disable proxy functionality
  enabled = false

  # Proxy port configuration
  proxy_port = 3000

[screen]
  # Clear terminal screen on rebuild
  clear_on_rebuild = true

  # Keep scrollback buffer in terminal
  keep_scroll = true
